services:
  newegg-scraper:
    build: .
    container_name: newegg-scraper
    volumes:
      # Mount data directory for persistent storage
      - ./data:/app/data
      # Mount logs directory (optional)
      - ./logs:/app/logs
    environment:
      # Scraper selection
      SCRAPER_TYPE: "enhanced"  # Options: "basic" or "enhanced"
      
      # Database configuration
      DUCKDB_PATH: "/app/data/newegg_data.duckdb"
      
      # Scraper configuration
      HEADLESS: "false"
      MAX_REVIEW_PAGES: "3"
      REQUEST_DELAY: "1.0"
      
      # Enhanced scraper specific settings
      USER_AGENT_STRATEGY: "weighted"  # Options: "random", "sequential", "weighted"
      MAX_WORKERS: "2"  # For concurrent scraping
      RATE_LIMIT_PER_SECOND: "0.5"  # For enhanced rate limiting
      
      # Output configuration
      OUTPUT_DIR: "/app/data"
      EXPORT_CSV: "false"
      
      # Logging configuration
      LOG_LEVEL: "INFO"
      LOG_FILE: "/app/logs/scraper.log"
      
      # Optional: Add any other environment variables
      PYTHONUNBUFFERED: "1"
    # Optional: Add restart policy for production
    # restart: unless-stopped
    # Optional: Add resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #       cpus: '1.0'
    #     reservations:
    #       memory: 1G
    #       cpus: '0.5'

  # Database query service
  db-query:
    build: .
    container_name: newegg-db-query
    volumes:
      # Mount data directory to access the database
      - ./data:/app/data
      # Mount current directory for output files
      - .:/app/output
    environment:
      # Database configuration
      DUCKDB_PATH: "/app/data/newegg_data.duckdb"
      PYTHONUNBUFFERED: "1"
    # Use bash as entrypoint to allow passing arguments
    entrypoint: ["python", "query_db.py", "--docker"]
    # This service is for interactive use, so we don't want it to start automatically
    profiles:
      - query

  # Optional: Add a simple web interface for viewing data
  # web-interface:
  #   build: ./web-interface
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./data:/app/data:ro
  #   depends_on:
  #     - newegg-scraper 